/* ACCOUNT SERVICE DATABASE LOAD */

DROP ROLE IF EXISTS account;
CREATE ROLE account LOGIN ENCRYPTED PASSWORD 'account' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
DROP DATABASE IF EXISTS account;
CREATE DATABASE account WITH OWNER = account ENCODING = 'UTF8' TABLESPACE = pg_default LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8' CONNECTION LIMIT = -1;
\connect listbus;

--CREATE SCHEMA CORE
DROP SCHEMA IF EXISTS account_service_schema CASCADE;
CREATE SCHEMA account_service_schema AUTHORIZATION account;
GRANT ALL ON SCHEMA account_service_schema TO account;
COMMENT ON SCHEMA account_service_schema IS 'Defines the database structure of the application';

--CREATE SEQUENCE CORE
DROP SEQUENCE IF EXISTS account_service_schema.USERS_IDUSER_SEQ;
CREATE SEQUENCE account_service_schema.USERS_IDUSER_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

--CREATE TABLES ACCOUNT SERVICE
CREATE TABLE account_service_schema.Users (
  idUser INTEGER NOT NULL DEFAULT NEXTVAL('account_service_schema.USERS_IDUSER_SEQ'),
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL
);
ALTER TABLE account_service_schema.Users ADD CONSTRAINT PKEY_BY_IDUSER PRIMARY KEY(idUser);

--SELECT TEST ACCOUNT SERVICE DATABASE
SELECT * FROM account_service_schema.Users;
